name: uda_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets section - CORRECT path (no 'lib/' prefix)
  assets:
    - assets/images/logo.png
    - assets/images/main.PNG
    - assets/images/main2.PNG
    - assets/images/Ruto.png
    - assets/images/H.E Cecily Mbarire.PNG
    - assets/images/H.E Prof. Kithure Kindiki.PNG
    - assets/images/Hon. Japheth Nyakundi.PNG
    - assets/images/Hon. Sen. Hassan Omar.PNG
    - assets/images/Mr. Kelvin Lunani.PNG
    - assets/images/Mr. Nicodemus Bore.PNG
    - assets/images/Omboko Milemba.PNG
    - assets/images/William Ruto.PNG
    - assets/images/H.E Issa Timamy.png
    - assets/images/news images/pic6.PNG
    - assets/images/news images/pic14.PNG 
    - assets/images/news images/pic13.PNG 
    - assets/images/news images/pic12.PNG 
    - assets/images/news images/pic11.PNG 
    - assets/images/news images/pic10.PNG 
    - assets/images/news images/pic9.PNG 
    - assets/images/news images/pic8.PNG 
    - assets/images/news images/pic7.PNG 
    - assets/images/news images/pic6.PNG 
    - assets/images/news images/pic5.PNG 
    - assets/images/news images/pic3.PNG 
    - assets/images/news images/Pic1.PNG 
    - assets/images/news images/19.PNG 
    - assets/images/news images/18.PNG 
    - assets/images/news images/17.PNG 
    - assets/images/news images/16.PNG 
    - assets/images/news images/15.PNG 

